"""Constants and keyword lists for email processing."""

import re

# Common cryptocurrency exchanges and platforms
CRYPTO_EXCHANGES = {
    # Major global exchanges
    "coinbase",
    "binance",
    "kraken",
    "bitfinex",
    "bitstamp",
    "gemini",
    "huobi",
    "okx",
    "kucoin",
    "crypto.com",
    "ftx",
    "bybit",
    "gate.io",
    "bittrex",
    "poloniex",
    # Mid-tier exchanges
    "coinex",
    "bitmart",
    "mexc",
    "bitget",
    "lbank",
    "probit",
    # Australian exchanges
    "coinspot",
    "independent reserve",
    "btcmarkets",
    "swyftx",
    # Canadian exchanges
    "coinsquare",
    "bitbuy",
    "newton",
    "coinhub",
    "ndax",
    # P2P and decentralized
    "localbitcoins",
    "paxful",
    "bisq",
    # European exchanges
    "bitvavo",
    "luno",
    "bitpanda",
    "coinmama",
    # Asian exchanges
    "upbit",
    "bithumb",
    "korbit",
    "zaif",
    "bitflyer",
    "liquid",
    # Latin American
    "mercado bitcoin",
    "bitso",
    "ripio",
    # US-specific
    "coinbase pro",
    "coinbase exchange",
    "robinhood crypto",
    "cash app",
    "paypal",
    "venmo",
    # Others
    "cex.io",
    "changelly",
    "shapeshift",
}

# Cryptocurrency names and symbols
CRYPTOCURRENCY_TERMS = {
    # Major cryptocurrencies
    "bitcoin",
    "btc",
    "ethereum",
    "eth",
    "litecoin",
    "ltc",
    "bitcoin cash",
    "bch",
    "ripple",
    "xrp",
    "cardano",
    "ada",
    "polkadot",
    "dot",
    "chainlink",
    "link",
    "stellar",
    "xlm",
    "dogecoin",
    "doge",
    "polygon",
    "matic",
    "solana",
    "sol",
    "avalanche",
    "avax",
    "terra",
    "luna",
    "cosmos",
    "atom",
    "algorand",
    "algo",
    "tezos",
    "xtz",
    "monero",
    "xmr",
    "zcash",
    "zec",
    "dash",
    "neo",
    "eos",
    "tron",
    "trx",
    "iota",
    "miota",
    "vechain",
    "vet",
    "qtum",
    "ont",
    "zil",
    # Stablecoins
    "tether",
    "usdt",
    "usd coin",
    "usdc",
    "binance usd",
    "busd",
    "dai",
    "tusd",
    "true usd",
    "pax",
    "paxos",
    "usdd",
    "frax",
    # Popular DeFi tokens
    "uniswap",
    "uni",
    "aave",
    "compound",
    "comp",
    "maker",
    "mkr",
    "synthetix",
    "snx",
    "curve",
    "crv",
    # Layer 2 and scaling
    "arbitrum",
    "arb",
    "optimism",
    "op",
    "immutable",
    "imx",
    # Memecoins
    "shiba inu",
    "shib",
    "pepe",
    "floki",
    # General terms
    "cryptocurrency",
    "crypto",
    "digital currency",
    "digital asset",
    "altcoin",
    "token",
    "coin",
}

# Purchase-related keywords
PURCHASE_KEYWORDS = {
    "purchase",
    "bought",
    "buy",
    "order",
    "transaction",
    "payment",
    "receipt",
    "confirmation",
    "executed",
    "filled",
    "completed",
    "successful",
    "acquired",
    "deposit",
    "withdrawal",
    "trade",
    "exchange",
    "convert",
    "swap",
    "market order",
    "limit order",
    "instant buy",
    "recurring buy",
    "auto-invest",
    "staking",
    "reward",
    "earned",
    "distribution",
    "trade confirmation",
    "order execution",
}

# Email patterns that indicate non-purchase content
NON_PURCHASE_PATTERNS = {
    "newsletter",
    "unsubscribe",
    "marketing",
    "promotion",
    "survey",
    "feedback",
    "educational",
    "news",
    "update",
    "announcement",
    "blog",
    "article",
    "webinar",
    "invite",
    "referral program",
    "contest",
    "giveaway",
    "airdrop notification",
    "price alert",
    "market analysis",
    "weekly report",
    "monthly summary",
    "login alert",
    "new login",
    "login detected",
    "device detected",
    "device confirmation",
    "unauthorized login",
    "suspicious activity",
    "2FA",
    "security alert",
    "security notification",
    "sign-in",
    "password reset",
    "account verification",
    "identity verification",
    "kyc update",
    "account locked",
    "account disabled",
    "terms of service",
    "privacy policy",
}

# Compiled regex patterns for high-performance keyword matching
CRYPTO_EXCHANGES_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(ex) for ex in CRYPTO_EXCHANGES) + r")\b", re.IGNORECASE
)
CRYPTOCURRENCY_TERMS_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(term) for term in CRYPTOCURRENCY_TERMS) + r")\b", re.IGNORECASE
)
PURCHASE_KEYWORDS_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(kw) for kw in PURCHASE_KEYWORDS) + r")\b", re.IGNORECASE
)
NON_PURCHASE_PATTERNS_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(p) for p in NON_PURCHASE_PATTERNS) + r")\b", re.IGNORECASE
)
